# qa (calidad) , dev (desarrollo), prod (produccion)
spring:
  application:
    name: mia-seguros-hijomenormayor
  profiles:
    active: ${PROFILES:dev,qa}
  config:
    import: configserver:${CONFIG_SERVER_URL}
  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}

