#Configuracion de datasource
server:
  port: 80
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@172.20.0.138:1521:DBSAS
    username: usrcsa
    password: usrcsa22

